### ISSUE TITLE
Documentation Refers to a Wrong Template Name

### ISSUE THREAD

**Issue by shurick81** [pnp/AdaptiveCards-Templates#2]
### Sample

https://github.com/pnp/AdaptiveCards-Templates/blob/50c9e786280017906ff0b4778c3583c27bc713ae/samples/benefits/README.md?plain=1#L25

### Author(s)

Max Kulakov, Microsoft & [Vesa Juvonen](https://github.com/vesajuvonen) ([@vesajuvonen](https://twitter.com/vesajuvonen)), Microsoft

### What happened?

in every template readme the line refers to `event-schedule`

### Steps to reproduce

1. open https://github.com/pnp/AdaptiveCards-Templates/blob/50c9e786280017906ff0b4778c3583c27bc713ae/samples/benefits/README.md?plain=1#L25

### Expected behavior

it should refer to `benefits` template, not `event-schedule`

### Target SharePoint environment

SharePoint Online

### Developer environment

Linux

### Browsers

- [ ] Internet Explorer
- [ ] Microsoft Edge
- [X] Google Chrome
- [ ] FireFox
- [ ] Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Node.js version

v14.18.0

**Comment by VesaJuvonen** [comment]
Fixed on the readme files. Thx @shurick81 for noticing.
